common:
  leverage: 1.0
  lossCutPercentage: 0.0
  positionClear: false #動作確認時はfalse
  firstTrade: BUY
exchange:
  apiKey: ""
  secret: ""
logic:
  trailPercentage: 0.0
  spread: 0.0
  notifyInterval: 60.0
slack:
  incomingWebhook: ""
